## Info Dump Analysis
# Kind of like a data editor, I will be creating
# a new story from an existing infographic.
# I am grateful for the work of the original creator Visual Capitalist, 
# this graphic inspired me to tell a new story.

# I found this infographic from Visual Capitalist showing how Earth's surface is divided up.

# Source: https://www.visualcapitalist.com/visualizing-the-abundance-of-elements-in-the-earths-crust/

# The data comes from UN Statistics Division and Protected Planet. 
# I want to break it down and see: who actually "owns" the planet?

In [ ]:
# Import pandas
# Read first CSV
import pandas as pd

df = pd.read_csv('earth_surface_data.csv')
df

                     country  land_percent category
0                     Russia          3.34     land
1                     Canada          1.96     land
2                      China          1.88     land
3              United States          1.87     land
4                     Brazil          1.67     land
5                  Australia          1.51     land
6                      India          0.64     land
7                  Argentina          0.55     land
8                 Kazakhstan          0.53     land
9                    Algeria          0.47     land
10                       DRC          0.46     land
11                 Greenland          0.42     land
12              Saudi Arabia          0.42     land
13                    Mexico          0.39     land
14                 Indonesia          0.37     land
15                     Libya          0.34     land
16                     Sudan          0.34     land
17                      Iran          0.32     land
18                  Mongolia          0.31     land
19                      Peru          0.25     land
20             Rest of World         14.00     land
21                Antarctica          2.75    other
22  Territorial Waters + EEZ         27.00    ocean
23      International Waters         43.00    ocean

In [ ]:
## Takeaways

# Russia's share is a lot larger than all nations with 3.34%
# Still a small portio of the entire planet

In [52]:
## Questions

#I still don't really know what the difference between
# International Waters and Territorial Waters.
# What is EEZ? I will figure out

# EEZ is a Exclusive Economic Zone

In [53]:
# Look at totals
# Group categories

df.groupby('category')['land_percent'].sum()

category
land     32.04
ocean    70.00
other     2.75
Name: land_percent, dtype: float64

In [54]:
# Fascinating, I read elsewhere it was 71 29 or something.
# Glad to have the total numbers

# Written Analysis
# So all the land, including every country and every border we've ever fought over is about 30% of Earth.
# Territorial waters add 27%. 
# But international waters? 43%. The biggest chunk (being the OCEAN) belongs to no one.

In [55]:
# Coding
                                                                                                                                  
land_only = df[df['category'] == 'land'].sort_values('land_percent', ascending=False)                                                            
land_only

          country  land_percent category
20  Rest of World         14.00     land
0          Russia          3.34     land
1          Canada          1.96     land
2           China          1.88     land
3   United States          1.87     land
4          Brazil          1.67     land
5       Australia          1.51     land
6           India          0.64     land
7       Argentina          0.55     land
8      Kazakhstan          0.53     land
9         Algeria          0.47     land
10            DRC          0.46     land
12   Saudi Arabia          0.42     land
11      Greenland          0.42     land
13         Mexico          0.39     land
14      Indonesia          0.37     land
15          Libya          0.34     land
16          Sudan          0.34     land
17           Iran          0.32     land
18       Mongolia          0.31     land
19           Peru          0.25     land

In [56]:
# Focusing on the land                                                                                                                      
                                                                                                                                                   
# Russia is the biggest at 3.34%, but that's still only 3% of Earth. The top 10 countries together are about 13%. All those borders for 13%

In [57]:
# Coding
top_10 = land_only.head(10)
top_10['land_percent'].sum()

np.float64(27.95)

In [58]:
# The 27% is a bit misleading because it includes “Rest of World” 
# as one of the top entries, which is basically lumping most countries
# together into one category. If you take that out, the top 10 individual
# countries only make up about 13%, 
# which shows how spread out land really is

In [59]:
# Even the biggest countries only
# take up small pieces of the planet,
# with Russia at just 3.34%,
# while everything else combined still makes up a much larger share at 14%.
chart1 = pd.read_csv('chart1_packed_bubbles.csv')                                                      
chart1

          country  percent  diameter_desktop  diameter_mobile
0          Russia     3.34                91               55
1          Canada     1.96                70               42
2           China     1.88                69               41
3   United States     1.87                68               41
4          Brazil     1.67                65               39
5       Australia     1.51                61               37
6           India     0.64                40               24
7       Argentina     0.55                37               22
8      Kazakhstan     0.53                36               22
9         Algeria     0.47                34               21
10  Rest of World    14.00               187              112

In [60]:
# I didn’t expect the biggest countries
# to be such small slices of the planet, 
# it makes everything feel way more
#  spread out than I thought.

In [ ]:
# After looking at individual countries,
# it makes more sense to step back and see how the planet
# is divided at a higher level.
chart2 = pd.read_csv('chart2_three_categories.csv')                                                    
chart2

                   category  percent  diameter_desktop  diameter_mobile
0                  All Land       30               274              165
1  Territorial Waters (EEZ)       27               260              156
2      International Waters       43               328              197

In [65]:
# What surprised me is how much of the planet 
# is just international waters at 43%, while all land together is smaller,
#and even the largest country looks tiny in comparison.

In [ ]:
# It’s still hard to grasp just from percentages,
# so I wanted to see what this looks like in terms of scale.                                                                                       
chart3 = pd.read_csv('chart3_scale_comparison.csv')                                                    
chart3

,item,percent,diameter_desktop,diameter_mobile,note
0,International Waters,43.00,400,240,main circle
1,All Land,30.00,334,200,reference
2,Russia,3.34,111,67,smallest reference

In [68]:
# Even when you scale it visually, it’s kind of striking that all land is
# still smaller than international waters, 
# and even Russia ends up looking tiny next to both.